# Generated by Django 5.2.dev20240812133519 on 2024-08-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbgeneral',
            name='test_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dbgeneral',
            name='test_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dbgeneral',
            name='test_3',
            field=models.IntegerField(),
        ),
    ]
