# Generated by Django 5.2.dev20240812133519 on 2024-08-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_list', '0002_alter_dbgeneral_test_1_alter_dbgeneral_test_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('surname', models.TextField()),
                ('city', models.TextField()),
                ('is_married', models.BooleanField()),
                ('bday', models.DateField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dbgeneral',
            name='test_1',
            field=models.JSONField(),
        ),
    ]
